// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CheckSyncStatus(arg1:models.SkillInfo,arg2:string):Promise<models.SyncStatus>;

export function DetectCliTools():Promise<Array<models.ToolStatus>>;

export function GetGitStatus(arg1:string):Promise<models.GitStatus>;

export function ImportSkillFolder(arg1:string,arg2:string):Promise<models.SkillInfo>;

export function LoadSettings():Promise<models.AppSettings>;

export function LogHistory():Promise<Array<models.LogEntry>>;

export function OpenPath(arg1:string):Promise<void>;

export function SaveSettings(arg1:models.AppSettings):Promise<void>;

export function ScanSkills(arg1:string):Promise<Array<models.SkillInfo>>;

export function SelectRootFolder():Promise<string>;

export function SelectSkillFolder():Promise<string>;

export function SyncSkillToTool(arg1:models.SkillInfo,arg2:string):Promise<models.SyncStatus>;
